### ISSUE TITLE
pygosemsim folder is empty

### ISSUE THREAD

**Issue by yuzhiguo07** [YasCoMa/ppi_validation_process#1]
Traceback (most recent call last):
  File "find_pattern.py", line 1, in <module>
    from pygosemsim import graph, download
ImportError: cannot import name 'graph' from 'pygosemsim' (unknown location)

**Comment by YasCoMa** [comment]
Thanks, i added the zipped file concerning the pygosemsim dependency and instructions to unzip it in the readme!
